- name: Drift check - SSH config
  hosts: "{{ HOSTS }}"
  become: true
  tasks:
    - name: Check if root login is permitted in SSH config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
      check_mode: true
      register: ssh_config_check

    - name: Report drift if SSH config is not compliant
      ansible.builtin.debug:
        msg: "Drift detected: SSH PermitRootLogin is not set to 'no'"
      when: ssh_config_check.changed
