- name: Install and start and Apache server
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Ensure the httpd package is insalled
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Create the index.html file
      ansible.builtin.template:
        src: /home/lab-user/files/index.html
        dest: /var/www/html/

    - name: Start the httpd service if needed
      ansible.builtin.service:
        name: httpd
        state: started
