---
- name: Enforce security baseline
  hosts: "{{ HOSTS }}"
  become: true
  tasks:
    - name: Ensure chronyd is installed and enabled
      ansible.builtin.yum:
        name: chrony
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure SSH root login is disabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        backup: yes
      notify: Restart SSH

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted