- name: Ruleset for file watching
  hosts: all
  gather_facts: true

  sources:
    - ansible.eda.file_watch:
          path: "/home/lab-user/app/"
          recursive: false
          ignore_regexes: [ '.*\.o' ]

  rules: 
    - name: trigger on deleted
      condition: event.change == "deleted"
      action:
        run_job_template:
          name: pwd
          organization: Default