- name: Ruleset for file watching
  hosts: rhel1

  sources:
    - ansible.eda.file_watch:
          path: "/home/"
          recursive: false
          ignore_regexes: [ '.*\.o' ]

  rules:
    - name: run tests 1
      condition: event.type == "DirModifiedEvent"

  ## Define the action we should take should the condition be met

      action:
          run_job_template:
            name: pwd
            organization: Default