- name: Ruleset for file watching
  hosts: all
  sources:
    - file_watch:
        path: "./home/labuser/app"

  rules: 
    - name: trigger on deleted
      condition: event.change == "deleted"
      action:
        run_job_template:
          name: create-file
          organization: Default