- name: Ruleset for file watching
  hosts: all
  sources:
    - ansible.eda.file_watch:
          path: "./app/"
          recursive: false
          ignore_regexes: [ '.*\.o' ]

  rules: 
    - name: trigger on deleted
      condition: event.change == "deleted"
      action:
        run_job_template:
          name: create-file
          organization: Default