- name: Ruleset for file watching
  hosts: all
  gather_facts: true

  sources:
    - ansible.eda.file_watch:
          path: "./"
          recursive: true
          ignore_regexes: [ '.*\.o' ]

  rules:
    - name: run tests 1
      condition: event.type == "DirModifiedEvent"

  ## Define the action we should take should the condition be met

      action:
          run_job_template:
            name: pwd
            organization: Default