- name: Ruleset for file watching
  hosts: all
  sources:
    - ansible.eda.file_watch:
        path: "/home/labuser/app/"
        recursive: false

  rules: 
    - name: trigger on deleted
      condition: event.change == "deleted"
      action:
        run_job_template:
          name: create-file
          organization: Default