- name: Ruleset for file watching
  hosts: all
  sources:
    - ansible.eda.file_watch:
          path: "./"
          recursive: false
          ignore_regexes: [ '.*\.o' ]

  rules: 
    - name: trigger on deleted
      condition: true
      action:
        run_job_template:
          name: pwd
          organization: Default