- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.file_watch:
        path: /home/lab-user/folder-to-watch
        recursive: true

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"

  ## Define the action we should take should the condition be met

      action:
          run_job_template:
            name: pwd
            organization: Default