- name: Listen for events on a webhook
  hosts: rhel1
  gather_facts: true

  ## Define our source for events

  sources:
    - ansible.eda.file_watch:
        path: ./
        recursive: true

  ## Define the conditions we are looking for

  rules:
    - name: run tests 1
      condition: event.type == "DirModifiedEvent"

  ## Define the action we should take should the condition be met

      action:
          run_job_template:
            name: pwd
            organization: Default